services:
  backend:
    image: kanesea-backend
    container_name: kanesea-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: kanesea-frontend
    container_name: kanesea-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus